name: Email Action Test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: 22f3002843@ds.study.iitm.ac.in
        run: echo "Hello, world!"
